language: cpp
sudo: false
services: docker
dist: trusty
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFBzaXJ1cyUzQW1hdHJpeC5vcmcvJTIxZG9KWEFCclp5VVBlV0Jmb0ZYJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

env:
    - BUILD_OPTIONS="-DCMAKE_CXX_COMPILER=clang++-4.0 -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=FALSE"
    - BUILD_OPTIONS="-DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=FALSE"
    - BUILD_OPTIONS="-DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=TRUE"
    - BUILD_OPTIONS="-DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_BUILD_TYPE=Debug -DENABLE_OPENMP=FALSE -DCMAKE_CXX_FLAGS=--coverage"

before_install:
    - ci_env=`bash <(curl -s https://codecov.io/env)`
    - echo $ci_env
    - docker pull nuto/nuto_docker:v2
    - docker run $ci_env -itd --user nuto --name dock -v $(pwd):/home/nuto/source nuto/nuto_docker:v3

script:
    # - We log in /home/nuto (set as WORKDIR in Dockerfile). This will be our build directory avoid changing directories.
    # - The source code from travis is 'mounted' as /home/nuto/source via the -v option in the docker run command above
    - docker exec dock cmake $BUILD_OPTIONS source
    - docker exec dock make -j2 unit

after_success:
    - docker exec dock bash source/scripts/upload_coverage.sh # will simply fail if --coverage is not set.
