language: cpp
sudo: required
dist: trusty
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFBzaXJ1cyUzQW1hdHJpeC5vcmcvJTIxZG9KWEFCclp5VVBlV0Jmb0ZYJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

jobs:
    include:
        - stage: normal builds
          env: BUILD_TYPE=Release OPENMP=FALSE
          compiler: clang
        - env: BUILD_TYPE=Release OPENMP=TRUE
          compiler: gcc
        - env: BUILD_TYPE=Release OPENMP=FALSE
          compiler: gcc
        - env: BUILD_TYPE=Debug   OPENMP=FALSE COVERAGE=--coverage
          compiler: gcc
        - stage: compiler warnings
          env: BUILD_TYPE=Debug   OPENMP=FALSE WERROR=-Werror
          compiler: gcc
        - env: BUILD_TYPE=Debug   OPENMP=FALSE WERROR=-Werror
          compiler: clang
    allow_failures:
        - env: BUILD_TYPE=Debug   OPENMP=FALSE WERROR=-Werror
    fast_finish: true

before_install:
    - export PATH=/home/travis/miniconda/bin:$PATH
    - ./scripts/install_numpy.sh
    - ./scripts/install_gmsh.sh
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get -qq install -y g++-6 clang libeigen3-dev libgcc-6-dev libiomp-dev swig3.0 libboost-filesystem1.55-dev libboost-test1.55-dev libboost-mpi1.55-dev libopenblas-dev libmetis-dev libmumps-seq-dev libann-dev libarpack2-dev lcov curl libglu1-mesa-dev
before_script:
    - mkdir build
    - cd build
    - BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_OPENMP=$OPENMP -DENABLE_MPI=TRUE"
    - if [[ "$CXX" == "g++" ]]; then CXX=g++-6 cmake $BUILD_OPTIONS -DCMAKE_CXX_FLAGS="$COVERAGE $WERROR" ..; fi
    - if [[ "$CXX" == "clang++" ]]; then CXX=clang++ cmake $BUILD_OPTIONS -DCMAKE_CXX_FLAGS="$COVERAGE $WERROR" ..; fi
script:
    - make -j2 unit
after_success:
    - cd ..
    - ./scripts/upload_coverage.sh
