language: cpp
sudo: false
services: docker
dist: trusty
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFBzaXJ1cyUzQW1hdHJpeC5vcmcvJTIxZG9KWEFCclp5VVBlV0Jmb0ZYJTNBbWF0cml4Lm9yZw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never
matrix:
    include:
        - compiler: clang
          env: BUILD_TYPE=Release OPENMP=FALSE
        - compiler: g++
          env: BUILD_TYPE=Release OPENMP=FALSE
        - compiler: g++
          env: BUILD_TYPE=Release OPENMP=TRUE
        - compiler: g++
          env: BUILD_TYPE=Debug OPENMP=FALSE COVERAGE=--coverage

before_install:
    - ci_env=`bash <(curl -s https://codecov.io/env)`
    - echo $ci_env
    - docker run $ci_env -itd --user nuto --name dock -v $(pwd):/home/nuto/source nuto/nuto_docker:xenial

script:
    # - We log in /home/nuto (set as WORKDIR in Dockerfile). This will be our build directory avoid changing directories.
    # - The source code from travis is 'mounted' as /home/nuto/source via the -v option in the docker run command above
    - docker exec dock cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_OPENMP=$OPENMP -DCMAKE_CXX_FLAGS=$COVERAGE source
    - docker exec dock make -j2 unit

after_success:
    - docker exec dock bash source/scripts/upload_coverage.sh # will simply fail if --coverage is not set.
